### ISSUE TITLE
Where and how to use config file?

### ISSUE THREAD

**Issue by IeuanWalker** [Soluto/oidc-server-mock#132]
I've added the config file to the route direct where the docker-compose files are - 
![image](https://github.com/Soluto/oidc-server-mock/assets/6544051/c6cff6e2-dd22-4124-9aa6-e9634b9c7d00)

I've added `oidc-server-mock` as a service in the docker-compose file -
```
version: '3.4'
volumes:
  db-data:
  
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - db-data:/var/opt/mssql/data
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Pa55w0rd2019"
        MSSQL_PID: Express
    ports:
        - "1433:1433"
  smtp-server:
    container_name: smtp-server
    image: mailhog/mailhog:latest
    restart: always
    logging:
     driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - ./test/azurite:/data

  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - '4011:80'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      API_SCOPES_INLINE: |
        - Name: some-app-scope-1
        - Name: some-app-scope-2
      API_RESOURCES_INLINE: |
        - Name: some-app
          Scopes:
            - some-app-scope-1
            - some-app-scope-2
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"User1",
            "Password":"pwd",
            "Claims": [
              {
                "Type": "name",
                "Value": "Sam Tailor",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "sam.tailor@gmail.com",
                "ValueType": "string"
              },
              {
                "Type": "some-api-resource-claim",
                "Value": "Sam's Api Resource Custom Claim",
                "ValueType": "string"
              },
              {
                "Type": "some-api-scope-claim",
                "Value": "Sam's Api Scope Custom Claim",
                "ValueType": "string"
              },
              {
                "Type": "some-identity-resource-claim",
                "Value": "Sam's Identity Resource Custom Claim",
                "ValueType": "string"
              }
            ]
          }
        ]
      CLIENTS_CONFIGURATION_PATH: /oidc-client-config.json
      ASPNET_SERVICES_OPTIONS_INLINE: |
        { 
          "ForwardedHeadersOptions": { 
            "ForwardedHeaders" : "All"
          }
        }
    volumes:
      - .:/tmp/config:ro

  admin:
    container_name: admin
    depends_on:
        - sql-server-db
        - smtp-server
        - azurite
    build:
      context: .
      dockerfile: Scr/Admin/Dockerfile
    ports:
        - "8080:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Developement
        - MailHostUrl=smtp-server
        - MailPort=1025
        - DatabaseConnections__EmailDb=Server=sql-server-db,1433;Initial Catalog=EmailTestData;User ID =SA;Password=Pa55w0rd2019;TrustServerCertificate=true;

  api:
    container_name: api
    depends_on:
        - sql-server-db
        - smtp-server
        - azurite
    build:
      context: .
      dockerfile: Scr/Api/Dockerfile
    ports:
        - "8010:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Developement
        - MailHostUrl=smtp-server
        - MailPort=1025
        - DatabaseConnections__EmailDb=Server=sql-server-db,1433;Initial Catalog=EmailTestData;User ID =SA;Password=Pa55w0rd2019;TrustServerCertificate=true;
```

But the `oidc-server-mock` container fails to start - 
```
2023-06-27 13:25:42 File name: '/oidc-client-config.json'
2023-06-27 13:25:42    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2023-06-27 13:25:42    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2023-06-27 13:25:42    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-06-27 13:25:42    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-06-27 13:25:42    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
2023-06-27 13:25:42    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
2023-06-27 13:25:42    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
2023-06-27 13:25:42    at System.IO.File.ReadAllText(String path)
2023-06-27 13:25:42    at OpenIdConnectServer.Config.GetClients() in /src/Config.cs:line 117
2023-06-27 13:25:42    at Program.<Main>$(String[] args) in /src/Program.cs:line 38
```

**Comment by AleF83** [comment]
Hey,
Thank you for checking out `oidc-server-mock`
I think that you should set the file as following: `CLIENTS_CONFIGURATION_PATH: ./oidc-client-config.json`

**Comment by IeuanWalker** [comment]
@AleF83 i've tried `./clients-config.json` and `../clients-config.json` and get the same error message.
If you want you can take a look at this branch - https://github.com/IeuanWalker/Email.io/tree/MockOCID

**Comment by IeuanWalker** [comment]
thanks, sorry this is the first project i've ever used docker for, so my knowledge is pretty low around docker

**Comment by agutierrezgit** [comment]
Try updating the `volumes` path. Check the example in E2E test.

**Comment by AleF83** [comment]
Closing due to inactivity and because it's the general Docker compose configuration issue
